# Generated by Django 4.0.6 on 2022-07-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('input_date', models.DateField(auto_now_add=True)),
                ('output_date', models.DateField(auto_now=True)),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='works.work')),
            ],
        ),
    ]
