# Generated by Django 4.0.6 on 2022-07-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
