<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-12 17:28
=======
# Generated by Django 4.0.6 on 2022-07-12 17:08
>>>>>>> categories

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('name', models.CharField(max_length=127)),
>>>>>>> categories
            ],
        ),
    ]
