# Generated by Django 4.0.6 on 2022-07-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliations', to='receipts.receipt')),
            ],
        ),
    ]
