# Generated by Django 4.0.6 on 2022-07-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='user',
            new_name='employee',
        ),
    ]
